name: Post to Instagram

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10 AM UTC
  workflow_dispatch:

jobs:
  instagram-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
        run: node post-to-instagram.js